"""
Django settings for gap project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from environ import Env

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")
ADMIN_KEY = env.str("ADMIN_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

PROJECT_NAME = "GAP"

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'controller.apps.ControllerConfig',
    'widget_tweaks',

    # ----- TailWindCSS ------#
    'tailwind',
    'theme',
    "django_htmx",
    "pwa",

    'academics.apps.AcademicsConfig',
    'teacher.apps.TeacherConfig',
    "timetable.apps.TimetableConfig",
    'users.apps.UsersConfig',
    'front.apps.FrontConfig'
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = 'gap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'controller.context_processors.global_data',
                'academics.context_processors.global_data',
                'users.context_processors.global_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'gap.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env.str("DB_NAME"),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '3306',
        'CONN_MAX_AGE': 0
    }
}

AUTHENTICATION_BACKENDS = [
    "users.backends.UsernameAuthBackend",
    "users.backends.EmailAuthBackend",
]

PASSWORD_HASHERS = [
    'users.utilities.hashers.argon2.Hasher',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = 'media/'
MEDIA_ROOT = env.str("MEDIA_ROOT")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "users:login"  # URL to the login page
LOGIN_REDIRECT_URL = "users:redirect-user"  # URL to redirect post-login

SECOND_FACTOR_VERIFICATION_URL = "users:email-factor"

LOCK_USER = False

AUTO_LOGOUT_DELAY = 1209600

MIN_LOGIN_ATTEMPT_LIMIT = 5
MAX_LOGIN_ATTEMPT_LIMIT = 20

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env.str("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_HOST_USER = env("EMAIL_HOST_USER")  # Your Gmail ID
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")  # Google app password (use an app-specific password)
EMAIL_USE_TLS = True

EMAIL_OTP_NOT_LINK = True

# Token expiry configuration in minutes, hours, etc.
TOKEN_EXPIRY = {
    "minutes": 10  # Default is 10 minutes
}

OTP_LENGTH = 6  # Preferred length of OTP (4 or 6 digits)
OTP_EXPIRY = {
    "seconds": 30,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "logs/django.log",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
# PWA Settings
PWA_APP_NAME = 'GAP'
PWA_APP_DESCRIPTION = "Greenvalley Academy Portal"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = "/accounts/login/"
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        "src": "/static/image/ico/favicon-circle.png",
        "sizes": "192x192",
        "type": "image/png",
        "purpose": "any"
    },
]
PWA_APP_SPLASH_SCREEN = [{'src': '/static/images/splash-640x1136.png', 'media': '(device-width: 320px)'}]
PWA_APP_SCREENSHOTS = [
    {
        'src': '/static/images/screenshots/desktop-screenshot.png',
        'sizes': '1312x663',
        'type': 'image/png',
        'form_factor': 'wide',  # Required for desktop
        'label': 'GAP Desktop View'
    },
    {
        'src': '/static/images/screenshots/mobile-screenshot.png',
        'sizes': '320x711',
        'type': 'image/png',
        # No form_factor = mobile (or set to 'narrow')
        'label': 'GAP Mobile View'
    },
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
